### ISSUE TITLE
About DIML/CVL dataset

### ISSUE THREAD

**Issue by puyiwen** [YuhangMing/PhD-Notes#1]
Hi, I am using the DIML/CVL dataset to estimate depth map. I have read the report of DIML/CVL, I still not sure how to preprocess the depth dataset. I want to process the depth map with `depth_map / 1000` so that it is a depth map in meters, am I doing this right? Thank you very much,and looking forward to your reply!!

**Comment by YuhangMing** [comment]
1000 is the most likely scale value. Though you need to contact the authors to be 100% sure.
